blank_issues_enabled: false
contact_links:
  - name: "Questions / discussions"
    url: "https://github.com/mini-bicasl/open-verilog-workbench/discussions"
    about: "If you're not sure which template to use, start a discussion."
